version: "3.7"

services:
  auth:
    image: bookswap/auth
    restart: always
    volumes:
      - auth_node_modules:/usr/src/app/node_modules
    command: npm run start:prod
    environment:
      NODE_ENV: production
    secrets:
      - json_web_token_secret
    depends_on:
      - db

  user:
    image: bookswap/user
    restart: always
    volumes:
      - user_node_modules:/usr/src/app/node_modules
    command: npm run start:prod
    environment:
      NODE_ENV: production
    secrets:
      - json_web_token_secret
    depends_on:
      - db

  book:
    image: bookswap/book
    restart: always
    volumes:
      - book_node_modules:/usr/src/app/node_modules
    command: npm run start:prod
    environment:
      NODE_ENV: production
    secrets:
      - json_web_token_secret
    depends_on:
      - db

  query:
    image: bookswap/query
    restart: always
    volumes:
      - query_node_modules:/usr/src/app/node_modules
    command: npm run start:prod
    environment:
      NODE_ENV: production
    secrets:
      - json_web_token_secret
      - goodreads_key_secret

  db:
    image: mongo:4.0-xenial
    restart: always
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:1.17
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - auth
      - user
      - book
      - query
      - db

volumes:
  auth_node_modules:
  user_node_modules:
  book_node_modules:
  query_node_modules:
  mongo_data:

secrets:
  json_web_token_secret:
    external: true
  goodreads_key_secret:
    external: true
