version: "3.7"

services:
  auth:
    build: ./auth
    restart: always
    volumes:
      - auth_node_modules:/usr/src/app/node_modules
    expose:
      - 8080
    command: npm run start:prod
    networks:
      - intern
      - public
    environment:
      NODE_ENV: production
      JWT_SECRET: /run/secrets/json_web_token_secret
    secrets:
      - json_web_token_secret
    depends_on:
      - db

  user:
    build: ./user
    restart: always
    volumes:
      - user_node_modules:/usr/src/app/node_modules
    expose:
      - 8080
    command: npm run start:prod
    networks:
      - intern
      - public
    environment:
      NODE_ENV: production
      JWT_SECRET: /run/secrets/json_web_token_secret
    secrets:
      - json_web_token_secret
    depends_on:
      - db

  book:
    build: ./book
    restart: always
    volumes:
      - book_node_modules:/usr/src/app/node_modules
    expose:
      - 8080
    command: npm run start:prod
    networks:
      - intern
      - public
    environment:
      NODE_ENV: production
      JWT_SECRET: /run/secrets/json_web_token_secret
    secrets:
      - json_web_token_secret
    depends_on:
      - db

  query:
    build: ./query
    restart: always
    volumes:
      - query_node_modules:/usr/src/app/node_modules
    expose:
      - 8080
    command: npm run start:prod
    networks:
      - intern
      - public
    environment:
      NODE_ENV: production
      JWT_SECRET: /run/secrets/json_web_token_secret
      GOODREADS_KEY: /run/secrets/goodreads_key_secret
    secrets:
      - json_web_token_secret
      - goodreads_key_secret

  db:
    image: mongo:4.0-xenial
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - intern

  nginx:
    image: nginx:1.17
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - public
    depends_on:
      - auth
      - user
      - book
      - query
      - db

volumes:
  auth_node_modules:
  user_node_modules:
  book_node_modules:
  query_node_modules:
  mongo_data:

networks:
  intern:
    driver: bridge
    internal: true
  public:
    driver: bridge

secrets:
  json_web_token_secret:
    external: true
  goodreads_key_secret:
    external: true
